### ISSUE TITLE
panning with middle mouse button

### ISSUE THREAD

**Issue by mschweikardt** [Circuit2TikZ/CircuiTikZ-Designer#26]
Hi, thanks for providing CircuiTikZ as GUI - Great work!

From my perspective, panning should be set on the middle mouse button (see attached patch) and not the right mouse button. 
The right mouse button is IMHO the standard way to open a context menu.

[panning-middle-mouse-button.txt](https://github.com/user-attachments/files/16842044/panning-middle-mouse-button.txt)

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by JPWiedemann** [comment]
Thank you!

We thought about this as well and while I agree with you that normally, the right mouse button should open up a context menu in the browser, it's not that easy in this case. We want to be compatible with Apple devices which don't really have a middle mouse button to put the dragging onto. Since selecting components should also be easily available, we have two mouse buttons (left and right) available for two common actions (selecting and panning). This also puts us more inline with some circuit EDA tools like Keysight ADS, where panning is also on the right mouse button.

However, the UI controls in general are still somewhat WIP and we are not yet fully satisfied with them. If you have other suggestions, please feel free to put them into Issue #24
