### ISSUE TITLE
Add Labels / Text Support

### ISSUE THREAD

**Issue by dog-blood** [Circuit2TikZ/CircuiTikZ-Designer#29]
I have been utilizing this to draw up diagrams for notes in my electrical engineering classes, but as far as I can see, there is no way to add text, or any sort of label. It's pretty much the only thing stopping me from using this.

**Comment by JPWiedemann** [comment]
Hey, thanks for the feedback! Glad you like it. Adding labels via mathjax is currently in development in the feature branch. Should be ready soon so stay tuned!

**Comment by dog-blood** [comment]
Awesome thanks. I will seriously use this thing for multiple hours a day if that happens. Right now without labels its basically unusable for me. Is there any way I can help?

**Comment by JPWiedemann** [comment]
There is always the possibility to fork the project and submit pull requests if you would like to contibute. (But beware, the codebase is somewhat of a mess right now and I really need to get around to cleaning up, restructuring and refactoring everything soon). Currently I'm not sure how we would implement labels for node components, since I don't yet know all the factors determining their position in circuitikz (sometimes inside nodes like in op amps, sometimes next to nodes like for transistors). I'm also now sure if we should use the tikz key "label" or the curly brackets for the TikZ code generation. So still some questions and implementation details to figure out. At least the labeling for path components is already working in the feature branch. You can check that out if you like

**Comment by dog-blood** [comment]
I will take a look if I have time, I am just a full time student. Maybe I am horribly misinformed, but could you not just place an arbitrary invisible dot on the page and add a node with text? I just want to be able to slap text on the figure without having to manually move them around

**Comment by JPWiedemann** [comment]
Well, additional text apart from the node and path component labels will be added in the future (as will generic shapes like rectangles and circles) for slapping text somewhere on the page. For now though, it would be pretty weird if you could add labels to path components but not node components which is why this has priority for now.

**Comment by JPWiedemann** [comment]
@dog-blood Check out 0.4 on the website. You can now label path and node components and give them names for the generated tikz code. We still don't support generic text anywhere but this should help for now

**Comment by dog-blood** [comment]
@JPWiedemann Just checked it out! This is perfect. I will be using this extensively. Once the school year's over I would love to contribute.
